### ISSUE TITLE
Suggest using try-with-resources

### ISSUE THREAD

**Issue by GueniPlayz** [thelooter/IOStein-Abstimmung#12]
https://github.com/RainbowDashLabs/BasicSQLPlugin#try-with-resources

**Comment by thelooter** [comment]
I use a Singleton for the Connection so this isn't needed

**Comment by GueniPlayz** [comment]
> I use a Singleton for the Connection so this isn't needed

but u have to close the ps, you're not closing it

**Comment by thelooter** [comment]
Since I'm using SQLite this won't be a big issue since an open Filehandle isn't that bad until you reach a fairly big scale.
